version: "3.7"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 9999:80
        volumes:
            - /Users/yangqi/Sites/shangyou_web:/var/www/html
